[package]
name = "tokio-jobs"
version = "0.1.0"
authors = ["olvyko <olvyko@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
uuid = { version = "0.8", features = ["v4"] }
tokio = { version = "0.2.11", features = ["full"] }
